// supabase/functions/superadmin-operations/resilience/registry.ts
// LPU Events — Canonical Resilience Scenarios Catalog (Phase 10)

import { ResilienceScenarioRecord } from './types.ts';

export const CANONICAL_SCENARIOS: ResilienceScenarioRecord[] = [
  {
    scenario_key: 'provider.unavailable',
    name: 'Provider Outage Simulation',
    description: 'Simulates complete unavailability of external cloud provider adapter (HTTP 503 / connection refused)',
    category: 'PROVIDER_FAILURE',
    risk_level: 'MEDIUM',
    allowed_environments: ['DEVELOPMENT', 'STAGING'],
    is_destructive: false,
    enabled: true,
    expected_detection: 'Health probe marks provider UNAVAILABLE, alert rule evaluates failure, incident created if policy dictates',
    expected_recovery: 'Provider returns healthy probe, alert resolves, incident transitions to AUTO_RECOVERY',
    timeout_ms: 30000,
  },
  {
    scenario_key: 'provider.timeout',
    name: 'Provider API Latency Timeout',
    description: 'Simulates gateway/adapter timeout exceeding configured threshold when probing provider endpoints',
    category: 'PROVIDER_FAILURE',
    risk_level: 'LOW',
    allowed_environments: ['DEVELOPMENT', 'STAGING'],
    is_destructive: false,
    enabled: true,
    expected_detection: 'Probe latency spike recorded, probe fails with TIMEOUT status',
    expected_recovery: 'Subsequent probe completes within latency budget, status returns to HEALTHY',
    timeout_ms: 30000,
  },
  {
    scenario_key: 'telemetry.stale',
    name: 'Telemetry Ingestion Staleness',
    description: 'Simulates collection worker cessation leading to telemetry exceeding freshness thresholds',
    category: 'TELEMETRY_FAILURE',
    risk_level: 'LOW',
    allowed_environments: ['DEVELOPMENT', 'STAGING'],
    is_destructive: false,
    enabled: true,
    expected_detection: 'Stale telemetry detector flags latest collection >5m old, UI surfaces STALE warning indicator',
    expected_recovery: 'Collection run executes, latest_collection_run updates, STALE indicator clears',
    timeout_ms: 30000,
  },
  {
    scenario_key: 'telemetry.missing',
    name: 'Missing Metric Observations',
    description: 'Simulates absent metric readings from partial collection runs without fabricating zeroes',
    category: 'TELEMETRY_FAILURE',
    risk_level: 'LOW',
    allowed_environments: ['DEVELOPMENT', 'STAGING'],
    is_destructive: false,
    enabled: true,
    expected_detection: 'Data quality evaluator marks metric series INSUFFICIENT_DATA without triggering false positive alerts',
    expected_recovery: 'Telemetry collection resumes, valid metric points ingested, data quality restored to SUFFICIENT',
    timeout_ms: 30000,
  },
  {
    scenario_key: 'job.failure',
    name: 'Maintenance Job Execution Crash',
    description: 'Simulates unhandled exception in background maintenance job worker',
    category: 'JOB_FAILURE',
    risk_level: 'MEDIUM',
    allowed_environments: ['DEVELOPMENT', 'STAGING'],
    is_destructive: false,
    enabled: true,
    expected_detection: 'Job run record transitions to FAILED with error summary, JOB_FAILURE alert evaluates and creates incident',
    expected_recovery: 'Safe runbook job.retry_safe_run succeeds, next scheduled run finishes COMPLETED, incident resolves',
    timeout_ms: 45000,
  },
  {
    scenario_key: 'job.stale',
    name: 'Maintenance Job Cadence Stall',
    description: 'Simulates a scheduled maintenance job that has missed its expected execution window (>2x cadence)',
    category: 'JOB_FAILURE',
    risk_level: 'LOW',
    allowed_environments: ['DEVELOPMENT', 'STAGING'],
    is_destructive: false,
    enabled: true,
    expected_detection: 'Cadence evaluator flags job as STALE, JOB_STALENESS alert triggers',
    expected_recovery: 'Job executes and completes, last_run_at updates, STALE state clears',
    timeout_ms: 30000,
  },
  {
    scenario_key: 'alert.evaluator_interruption',
    name: 'Alert Evaluator Worker Interruption',
    description: 'Simulates sudden worker termination mid-evaluation, testing single-flight lease recovery and state continuity',
    category: 'ALERTING_FAILURE',
    risk_level: 'MEDIUM',
    allowed_environments: ['DEVELOPMENT', 'STAGING'],
    is_destructive: false,
    enabled: true,
    expected_detection: 'Active evaluation lock expires without releasing, lease recovery kicks in on next invocation',
    expected_recovery: 'Next evaluation cycle acquires lock, evaluates all rules, zero duplicate alerts or incidents created',
    timeout_ms: 30000,
  },
  {
    scenario_key: 'notification.provider_outage',
    name: 'Notification Delivery Provider Outage',
    description: 'Simulates Resend / email provider complete outage during critical incident dispatch',
    category: 'NOTIFICATION_FAILURE',
    risk_level: 'MEDIUM',
    allowed_environments: ['DEVELOPMENT', 'STAGING'],
    is_destructive: false,
    enabled: true,
    expected_detection: 'Delivery attempts transition to FAILED with retry schedule, anti-recursion stops notification alert loop',
    expected_recovery: 'Provider restores, delivery retry worker processes outbox queue, notification delivers successfully',
    timeout_ms: 45000,
  },
  {
    scenario_key: 'notification.worker_crash',
    name: 'Notification Outbox Worker Crash',
    description: 'Simulates outbox processor termination during batch delivery processing',
    category: 'NOTIFICATION_FAILURE',
    risk_level: 'LOW',
    allowed_environments: ['DEVELOPMENT', 'STAGING'],
    is_destructive: false,
    enabled: true,
    expected_detection: 'Claimed outbox items remain in PROCESSING until lock expiry, item not dropped',
    expected_recovery: 'Next delivery worker run reclaims stuck outbox items, dispatches cleanly without duplication',
    timeout_ms: 30000,
  },
  {
    scenario_key: 'remediation.worker_crash',
    name: 'Remediation Worker Crash Mid-Flight',
    description: 'Simulates termination while remediation is in EXECUTING state',
    category: 'REMEDIATION_FAILURE',
    risk_level: 'HIGH',
    allowed_environments: ['DEVELOPMENT', 'STAGING'],
    is_destructive: false,
    enabled: true,
    expected_detection: 'Remediation execution remains in EXECUTING, single-flight protects against concurrent duplicate runs',
    expected_recovery: 'Authoritative verification determines whether underlying action completed, reconciles to COMPLETED or FAILED',
    timeout_ms: 60000,
  },
  {
    scenario_key: 'remediation.timeout',
    name: 'Remediation Action Timeout',
    description: 'Simulates remediation handler exceeding action timeout budget',
    category: 'REMEDIATION_FAILURE',
    risk_level: 'MEDIUM',
    allowed_environments: ['DEVELOPMENT', 'STAGING'],
    is_destructive: false,
    enabled: true,
    expected_detection: 'Remediation transitions to FAILED with safe_error_code TIMEOUT, incident remains active',
    expected_recovery: 'Super Admin notified of remediation failure, runbook cooldown respected',
    timeout_ms: 45000,
  },
  {
    scenario_key: 'remediation.verification_failure',
    name: 'Remediation Post-Action Verification Mismatch',
    description: 'Simulates action execution returning 200/success but authoritative system condition failing verification',
    category: 'REMEDIATION_FAILURE',
    risk_level: 'MEDIUM',
    allowed_environments: ['DEVELOPMENT', 'STAGING'],
    is_destructive: false,
    enabled: true,
    expected_detection: 'Execution strictly marked FAILED (never false COMPLETED), safe_error_code POST_VERIFICATION_FAILED',
    expected_recovery: 'Incident remains OPEN, escalation continues, truthfulness preserved',
    timeout_ms: 30000,
  },
  {
    scenario_key: 'rollback.failure',
    name: 'Remediation Rollback Failure',
    description: 'Simulates failure during automated rollback execution',
    category: 'RECOVERY_FAILURE',
    risk_level: 'HIGH',
    allowed_environments: ['DEVELOPMENT', 'STAGING'],
    is_destructive: false,
    enabled: true,
    expected_detection: 'Rollback transitions to ROLLBACK_FAILED, incident timeline records failure event',
    expected_recovery: 'Super Admin alerted immediately, incident requires manual operator intervention',
    timeout_ms: 45000,
  },
  {
    scenario_key: 'remediation.duplicate_attempt',
    name: 'Concurrent Duplicate Remediation Flood',
    description: 'Simulates 100 simultaneous remediation execution requests for the same incident and action',
    category: 'REMEDIATION_FAILURE',
    risk_level: 'LOW',
    allowed_environments: ['DEVELOPMENT', 'STAGING'],
    is_destructive: false,
    enabled: true,
    expected_detection: 'Database uniqueness on idempotency_key and single-flight lock rejects 99 requests',
    expected_recovery: 'Exactly one effective remediation executed, zero duplicate side-effects',
    timeout_ms: 30000,
  },
  {
    scenario_key: 'analytics.rollup_failure',
    name: 'Historical Analytics Rollup Failure',
    description: 'Simulates rollup job timeout or query failure during hourly aggregation',
    category: 'COMBINED_FAILURE',
    risk_level: 'LOW',
    allowed_environments: ['DEVELOPMENT', 'STAGING'],
    is_destructive: false,
    enabled: true,
    expected_detection: 'Rollup job records failure, current operational dashboard and live probes remain 100% operational',
    expected_recovery: 'Next hourly rollup re-evaluates missed window with idempotent ON CONFLICT updates',
    timeout_ms: 45000,
  },
  {
    scenario_key: 'gateway.timeout',
    name: 'Operations Gateway Endpoint Timeout',
    description: 'Simulates Operations Gateway Edge Function timeout from client SDK perspective',
    category: 'NETWORK_FAILURE',
    risk_level: 'LOW',
    allowed_environments: ['DEVELOPMENT', 'STAGING'],
    is_destructive: false,
    enabled: true,
    expected_detection: 'Client SDK catches TIMEOUT error code, UI preserves last known good state with stale banner',
    expected_recovery: 'Gateway recovers, client refresh replaces stale data with authoritative fresh state',
    timeout_ms: 30000,
  },
  {
    scenario_key: 'combined.subsystem_failure',
    name: 'Multi-Subsystem Cascading Failure',
    description: 'Simulates simultaneous provider outage, notification delay, and stale telemetry',
    category: 'COMBINED_FAILURE',
    risk_level: 'HIGH',
    allowed_environments: ['DEVELOPMENT', 'STAGING'],
    is_destructive: false,
    enabled: true,
    expected_detection: 'Subsystems fail independently without cascading crash; incident created, notification queued, telemetry truth preserved',
    expected_recovery: 'Subsystems recover in isolation, each returning to HEALTHY without cross-subsystem deadlocks',
    timeout_ms: 60000,
  },
  {
    scenario_key: 'recovery.provider_outage',
    name: 'Full Natural Recovery After Provider Outage',
    description: 'Validates complete end-to-end recovery sequence without manual intervention',
    category: 'RECOVERY_FAILURE',
    risk_level: 'LOW',
    allowed_environments: ['DEVELOPMENT', 'STAGING'],
    is_destructive: false,
    enabled: true,
    expected_detection: 'Provider outage creates HIGH incident and dispatches notification',
    expected_recovery: 'Provider restores, probe succeeds, alert clears, incident automatically transitions to RESOLVED with AUTO_RECOVERY provenance',
    timeout_ms: 45000,
  },
  {
    scenario_key: 'recovery.job_failure',
    name: 'Maintenance Job Natural Recovery',
    description: 'Validates incident resolution when a previously failing maintenance job subsequently succeeds',
    category: 'RECOVERY_FAILURE',
    risk_level: 'LOW',
    allowed_environments: ['DEVELOPMENT', 'STAGING'],
    is_destructive: false,
    enabled: true,
    expected_detection: 'Failing job triggers incident',
    expected_recovery: 'Subsequent scheduled run finishes COMPLETED, alert evaluator marks alert resolved, incident auto-recovers',
    timeout_ms: 45000,
  },
  {
    scenario_key: 'recovery.remediation_assisted',
    name: 'Remediation-Assisted Recovery Sequence',
    description: 'Validates incident resolution achieved via approved remediation runbook execution',
    category: 'RECOVERY_FAILURE',
    risk_level: 'MEDIUM',
    allowed_environments: ['DEVELOPMENT', 'STAGING'],
    is_destructive: false,
    enabled: true,
    expected_detection: 'Incident triggers recommended runbook; runbook executed, verified, and records success event',
    expected_recovery: 'Authoritative state recovery closes incident, timeline records REMEDIATION_SUCCEEDED alongside resolution',
    timeout_ms: 60000,
  },
  {
    scenario_key: 'disaster_recovery.backup_validation',
    name: 'Production Backup Verification & Integrity Check',
    description: 'Validates existence, recency (<24h), encryption, and structural validity of production database backups',
    category: 'DISASTER_RECOVERY',
    risk_level: 'LOW',
    allowed_environments: ['DEVELOPMENT', 'STAGING', 'PRODUCTION'],
    is_destructive: false,
    enabled: true,
    expected_detection: 'Verifies backup catalog records valid timestamp, non-zero byte size, and encryption headers',
    expected_recovery: 'Restoration test into isolated staging target validates table counts and row integrity within RTO/RPO limits',
    timeout_ms: 60000,
  },
  {
    scenario_key: 'disaster_recovery.migration_replay',
    name: 'Database Migration Sequence Replay',
    description: 'Validates that full 53-migration canonical sequence can be replayed from scratch on fresh database',
    category: 'DISASTER_RECOVERY',
    risk_level: 'LOW',
    allowed_environments: ['DEVELOPMENT', 'STAGING'],
    is_destructive: false,
    enabled: true,
    expected_detection: 'All migrations execute in strict order without dependency failure or syntax error',
    expected_recovery: 'Schema parity check confirms complete table, function, index, and RLS constraint alignment',
    timeout_ms: 60000,
  },
];

export function getScenarioByKey(scenarioKey: string): ResilienceScenarioRecord | undefined {
  return CANONICAL_SCENARIOS.find((s) => s.scenario_key === scenarioKey);
}
