// supabase/functions/superadmin-operations/governance/registry.ts
// LPU Events — Phase 11: Canonical SLI, SLO & Capacity Registries

import { SliDefinition, SloDefinition, CapacityDefinition } from './types.ts';

export const CANONICAL_SLIS: SliDefinition[] = [
  {
    sli_key: 'platform.availability',
    name: 'Platform Services Availability',
    service_id: 'platform',
    metric_source: 'ops_health_probes',
    calculation_type: 'AVAILABILITY',
    unit: 'PERCENT',
    aggregation: 'RATIO',
    description: 'Ratio of successful health probes to total eligible probe evaluations',
    is_enabled: true,
  },
  {
    sli_key: 'worker.error_rate',
    name: 'Edge Function & Worker Error Rate',
    service_id: 'cloudflare',
    metric_source: 'ops_metric_snapshots',
    calculation_type: 'ERROR_RATE',
    unit: 'PERCENT',
    aggregation: 'RATIO',
    description: 'Ratio of worker HTTP 5xx errors to total worker request volume',
    is_enabled: true,
  },
  {
    sli_key: 'maintenance_jobs.success_rate',
    name: 'Maintenance Jobs Success Rate',
    service_id: 'supabase',
    metric_source: 'ops_job_runs',
    calculation_type: 'SUCCESS_RATE',
    unit: 'PERCENT',
    aggregation: 'RATIO',
    description: 'Ratio of COMPLETED job executions to total eligible terminal runs',
    is_enabled: true,
  },
  {
    sli_key: 'telemetry.freshness',
    name: 'Operational Telemetry Freshness',
    service_id: 'telemetry',
    metric_source: 'ops_collection_runs',
    calculation_type: 'FRESHNESS',
    unit: 'SECONDS',
    aggregation: 'LATEST',
    description: 'Elapsed time in seconds since the most recent telemetry collection run',
    is_enabled: true,
  },
  {
    sli_key: 'incidents.mttr',
    name: 'Mean Time to Recovery (MTTR)',
    service_id: 'platform',
    metric_source: 'ops_incidents',
    calculation_type: 'RECOVERY_TIME',
    unit: 'SECONDS',
    aggregation: 'AVERAGE',
    description: 'Average duration in seconds from incident open to verified resolution',
    is_enabled: true,
  },
  {
    sli_key: 'database.query_latency',
    name: 'Database Diagnostics Query Latency',
    service_id: 'database',
    metric_source: 'ops_health_probes',
    calculation_type: 'LATENCY',
    unit: 'MILLISECONDS',
    aggregation: 'P95',
    description: 'P95 latency of database diagnostics checks in milliseconds',
    is_enabled: true,
  },
];

export const CANONICAL_SLOS: SloDefinition[] = [
  {
    slo_key: 'slo.platform.availability',
    name: 'Core Platform 99.9% Availability Target',
    service_id: 'platform',
    sli_key: 'platform.availability',
    target: 99.90,
    window: '30d',
    direction: 'GREATER_EQUAL',
    warning_threshold: 99.95,
    description: 'Maintains >= 99.9% health probe availability over a rolling 30-day window',
    enabled: true,
    version: 1,
    effective_from: '2026-10-01T00:00:00Z',
    effective_to: null,
  },
  {
    slo_key: 'slo.worker.error_rate',
    name: 'Edge Worker Sub-1% Error Rate Target',
    service_id: 'cloudflare',
    sli_key: 'worker.error_rate',
    target: 1.00,
    window: '24h',
    direction: 'LESS_EQUAL',
    warning_threshold: 0.50,
    description: 'Maintains worker error rate <= 1.0% over rolling 24 hours',
    enabled: true,
    version: 1,
    effective_from: '2026-10-01T00:00:00Z',
    effective_to: null,
  },
  {
    slo_key: 'slo.maintenance.success_rate',
    name: 'Maintenance Jobs 95% Success Target',
    service_id: 'supabase',
    sli_key: 'maintenance_jobs.success_rate',
    target: 95.00,
    window: '7d',
    direction: 'GREATER_EQUAL',
    warning_threshold: 97.00,
    description: 'Maintains >= 95.0% completion rate for scheduled maintenance jobs over 7 days',
    enabled: true,
    version: 1,
    effective_from: '2026-10-01T00:00:00Z',
    effective_to: null,
  },
  {
    slo_key: 'slo.telemetry.freshness',
    name: 'Operational Telemetry 5-Minute Freshness Target',
    service_id: 'telemetry',
    sli_key: 'telemetry.freshness',
    target: 300.0,
    window: '24h',
    direction: 'LESS_EQUAL',
    warning_threshold: 240.0,
    description: 'Ensures telemetry collection latency stays under 300 seconds (5 minutes)',
    enabled: true,
    version: 1,
    effective_from: '2026-10-01T00:00:00Z',
    effective_to: null,
  },
  {
    slo_key: 'slo.incidents.mttr',
    name: 'Incident Recovery Time Under 1 Hour Target',
    service_id: 'platform',
    sli_key: 'incidents.mttr',
    target: 3600.0,
    window: '30d',
    direction: 'LESS_EQUAL',
    warning_threshold: 2700.0,
    description: 'Maintains MTTR under 3600 seconds (1 hour) for operational incidents',
    enabled: true,
    version: 1,
    effective_from: '2026-10-01T00:00:00Z',
    effective_to: null,
  },
];

export const CANONICAL_CAPACITY: CapacityDefinition[] = [
  {
    resource_key: 'capacity.database.storage',
    name: 'Database Storage Footprint',
    category: 'DATABASE',
    unit: 'BYTES',
    hard_limit: 536870912, // 512 MB
    soft_threshold_percent: 80.0,
    critical_threshold_percent: 90.0,
    source: 'ops_metric_snapshots:database_size_bytes',
    is_enabled: true,
  },
  {
    resource_key: 'capacity.r2.storage',
    name: 'Cloudflare R2 Media Storage Footprint',
    category: 'STORAGE',
    unit: 'BYTES',
    hard_limit: 10737418240, // 10 GB
    soft_threshold_percent: 80.0,
    critical_threshold_percent: 90.0,
    source: 'ops_metric_snapshots:r2_storage_bytes',
    is_enabled: true,
  },
  {
    resource_key: 'capacity.r2.objects',
    name: 'Cloudflare R2 Media Object Count',
    category: 'STORAGE',
    unit: 'COUNT',
    hard_limit: 100000,
    soft_threshold_percent: 80.0,
    critical_threshold_percent: 90.0,
    source: 'ops_metric_snapshots:r2_object_count',
    is_enabled: true,
  },
  {
    resource_key: 'capacity.notifications.outbox_queue',
    name: 'Operational Notification Outbox Backlog',
    category: 'QUEUE',
    unit: 'COUNT',
    hard_limit: 1000,
    soft_threshold_percent: 70.0,
    critical_threshold_percent: 90.0,
    source: 'ops_notification_outbox:pending_count',
    is_enabled: true,
  },
  {
    resource_key: 'capacity.remediation.queue',
    name: 'Remediation Active Execution Backlog',
    category: 'QUEUE',
    unit: 'COUNT',
    hard_limit: 50,
    soft_threshold_percent: 60.0,
    critical_threshold_percent: 80.0,
    source: 'ops_remediation_executions:executing_count',
    is_enabled: true,
  },
  {
    resource_key: 'capacity.resend.daily_emails',
    name: 'Resend Daily Outbound Email Volume',
    category: 'EMAIL',
    unit: 'COUNT',
    hard_limit: 3000,
    soft_threshold_percent: 80.0,
    critical_threshold_percent: 95.0,
    source: 'ops_metric_snapshots:resend_emails_sent',
    is_enabled: true,
  },
];

export function getSliByKey(key: string): SliDefinition | undefined {
  return CANONICAL_SLIS.find((s) => s.sli_key === key);
}

export function getSloByKey(key: string): SloDefinition | undefined {
  return CANONICAL_SLOS.find((s) => s.slo_key === key);
}

export function getCapacityResourceByKey(key: string): CapacityDefinition | undefined {
  return CANONICAL_CAPACITY.find((c) => c.resource_key === key);
}
